# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=75, null=True)),
                ('email', models.EmailField(blank=True, max_length=75, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=75, null=True)),
                ('isadmin', models.BooleanField()),
            ],
        ),
    ]
